name: movis_app
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.2.2
  flutter_bloc: ^9.0.0
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.2
  flutter_svg: ^2.0.17
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  iconly: ^1.0.1
  dio: ^5.2.1
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  # puld runner
  build_runner: ^2.4.11
  # Freezed annotation processor
  freezed: ^2.5.1
  # Freezed annotation processor
  freezed_annotation: ^2.4.4
  # Pretty Dio Logger
  pretty_dio_logger: ^1.3.0
  # Retrofit 
  retrofit: ^4.4.1
  # Retrofit Generator
  retrofit_generator: ^9.1.4
  equatable: ^2.0.5
  # A simple dependency injection framework
  get_it: ^8.0.3
  # esy way to loading 
  shimmer: ^3.0.0
  meta: ^1.15.0
  shared_preferences: ^2.3.5
  flutterfire_cli: ^1.0.1

  



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/movies_images/


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic